<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
    <Page Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\AccommodationImages\Accommodation11\13.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation13\hero-image.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation14\a.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation15\a.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation2\hero-image.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation4\sadsadsa.jpeg" />
    <None Remove="Resources\AccommodationImages\Accommodation5\image268.png" />
    <None Remove="Resources\AccommodationImages\Accommodation6\2857hotel-na-kopaoniku.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation7\Oakford.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation8\a.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation9\b.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation10\12.jpg" />
    <None Remove="Resources\Fonts\OpenSans-Italic-VariableFont_wdth,wght.ttf" />
    <None Remove="Resources\Fonts\OpenSans-VariableFont_wdth,wght.ttf" />
    <None Remove="Resources\Fonts\OpenSans_Condensed-Regular.ttf" />
    <None Remove="Resources\Images\add.png" />
    <None Remove="Resources\Images\delete.png" />
    <None Remove="Resources\Images\edit.png" />
    <None Remove="Resources\Images\GuideImages\Add Circle.png" />
    <None Remove="Resources\Images\GuideImages\Alt Arrow Down.png" />
    <None Remove="Resources\Images\GuideImages\Alt Arrow Left.png" />
    <None Remove="Resources\Images\GuideImages\Arrows ALogout 2.png" />
    <None Remove="Resources\Images\GuideImages\Chat Round Line.png" />
    <None Remove="Resources\Images\GuideImages\Clock Circle.png" />
    <None Remove="Resources\Images\GuideImages\Flag.png" />
    <None Remove="Resources\Images\GuideImages\Home.png" />
    <None Remove="Resources\Images\GuideImages\Lightbulb Minimalistic.png" />
    <None Remove="Resources\Images\GuideImages\Map Point Add.png" />
    <None Remove="Resources\Images\GuideImages\ns.jpeg" />
    <None Remove="Resources\Images\GuideImages\Play Circle.png" />
    <None Remove="Resources\Images\GuideImages\Question Circle.png" />
    <None Remove="Resources\Images\GuideImages\User Circle.png" />
    <None Remove="Resources\Images\GuideImages\User.png" />
    <None Remove="Resources\Images\GuestImages\ABCIcon.png" />
    <None Remove="Resources\Images\GuestImages\ApprovedIcon.png" />
    <None Remove="Resources\Images\GuestImages\BackIcon.png" />
    <None Remove="Resources\Images\GuestImages\BathIcon.png" />
    <None Remove="Resources\Images\GuestImages\BedsIcon.png" />
    <None Remove="Resources\Images\GuestImages\CalendarIcon.png" />
    <None Remove="Resources\Images\GuestImages\CheckIcon.png" />
    <None Remove="Resources\Images\GuestImages\ClockIcon.png" />
    <None Remove="Resources\Images\GuestImages\DaysIcon.png" />
    <None Remove="Resources\Images\GuestImages\HelpIcon.png" />
    <None Remove="Resources\Images\GuestImages\HouseIcon.png" />
    <None Remove="Resources\Images\GuestImages\InboxIcon.png" />
    <None Remove="Resources\Images\GuestImages\KnifeAndForkIcon.png" />
    <None Remove="Resources\Images\GuestImages\LocationIcon.png" />
    <None Remove="Resources\Images\GuestImages\NotificationIcon.png" />
    <None Remove="Resources\Images\GuestImages\OtherIcon.png" />
    <None Remove="Resources\Images\GuestImages\ParkingIcon.png" />
    <None Remove="Resources\Images\GuestImages\PersonIcon.png" />
    <None Remove="Resources\Images\GuestImages\RejectedIcon.png" />
    <None Remove="Resources\Images\GuestImages\SearchIcon.png" />
    <None Remove="Resources\Images\GuestImages\StarIcon.png" />
    <None Remove="Resources\Images\GuestImages\TravelBagIcon.png" />
    <None Remove="Resources\Images\GuestImages\UserIcon.png" />
    <None Remove="Resources\Images\GuestImages\WaitingIcon.png" />
    <None Remove="Resources\Images\GuestImages\WiFiIcon.png" />
    <None Remove="Resources\Images\GuestImages\XIcon.png" />
    <None Remove="Resources\Images\OwnerImages\loginPicture.jpg" />
    <None Remove="Resources\Images\OwnerImages\loginPicture1.jpg" />
    <None Remove="Resources\Images\view.png" />
    <None Remove="Resources\TourImages\Tour1\caption.jpg" />
    <None Remove="Resources\TourImages\Tour2\caption.jpg" />
    <None Remove="Resources\TourImages\Tour3\caption.jpg" />
    <None Remove="Resources\TourImages\Tour4\caption.jpg" />
    <None Remove="Resources\TourImages\Tour4\GFS_smederevo-trg-25-09-09-04.jpg" />
    <None Remove="Resources\TourImages\Tour5\download.jpeg" />
    <None Remove="Resources\TourImages\Tour6\GFS_smederevo-trg-25-09-09-04.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\OwnerImages\loginPicture1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\GuestImages\WaitingIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\AccommodationImages\Accommodation11\13.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation13\hero-image.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation14\a.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation15\a.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation2\hero-image.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation8\a.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation9\b.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation10\12.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation4\sadsadsa.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation5\image268.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation6\2857hotel-na-kopaoniku.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation7\Oakford.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\add.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\delete.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\edit.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Add Circle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Alt Arrow Down.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Alt Arrow Left.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Arrows ALogout 2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Chat Round Line.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Clock Circle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Flag.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Home.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Lightbulb Minimalistic.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Map Point Add.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\ns.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Play Circle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\Question Circle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\User Circle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuideImages\User.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\ABCIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\ApprovedIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\BackIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\BathIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\BedsIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\CalendarIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\CheckIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\ClockIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\DaysIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\HelpIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\HouseIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\InboxIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\KnifeAndForkIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\LocationIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\NotificationIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\OtherIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\ParkingIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\PersonIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\RejectedIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\SearchIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\StarIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\TravelBagIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\UserIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\WiFiIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\GuestImages\XIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\OwnerImages\loginPicture.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\view.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour1\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour2\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour3\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour4\GFS_smederevo-trg-25-09-09-04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour5\download.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour6\GFS_smederevo-trg-25-09-09-04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\OpenSans-Italic-VariableFont_wdth,wght.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\OpenSans-VariableFont_wdth,wght.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\OpenSans_Condensed-Regular.ttf" />
    <Folder Include="Resources\Images\GuestImages\" />
    <Folder Include="Resources\Images\GuideImages\" />
    <Folder Include="Resources\Images\TouristImages\" />
    <Folder Include="Resources\Images\OwnerImages\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\GuestImages\" />
    <Folder Include="Resources\Images\GuideImages\" />
    <Folder Include="Resources\Images\TouristImages\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="1.0.0.18" />
    <PackageReference Include="ToastNotifications" Version="2.5.1" />
    <PackageReference Include="ToastNotifications.Messages" Version="2.5.1" />
  </ItemGroup>

</Project>
