<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
    <Page Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\AccommodationImages\Accommodation11\13.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation13\hero-image.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation2\hero-image.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation4\sadsadsa.jpeg" />
    <None Remove="Resources\AccommodationImages\Accommodation5\image268.png" />
    <None Remove="Resources\AccommodationImages\Accommodation6\2857hotel-na-kopaoniku.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation7\Oakford.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation8\a.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation9\b.jpg" />
    <None Remove="Resources\AccommodationImages\Accommodation10\12.jpg" />
    <None Remove="Resources\Images\add.png" />
    <None Remove="Resources\Images\delete.png" />
    <None Remove="Resources\Images\edit.png" />
    <None Remove="Resources\Images\view.png" />
    <None Remove="Resources\TourImages\Tour1\caption.jpg" />
    <None Remove="Resources\TourImages\Tour2\caption.jpg" />
    <None Remove="Resources\TourImages\Tour3\caption.jpg" />
    <None Remove="Resources\TourImages\Tour4\caption.jpg" />
    <None Remove="Resources\TourImages\Tour4\GFS_smederevo-trg-25-09-09-04.jpg" />
    <None Remove="Resources\TourImages\Tour5\download.jpeg" />
    <None Remove="Resources\TourImages\Tour6\GFS_smederevo-trg-25-09-09-04.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\AccommodationImages\Accommodation11\13.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation13\hero-image.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation2\hero-image.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation8\a.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation9\b.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation10\12.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation4\sadsadsa.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation5\image268.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation6\2857hotel-na-kopaoniku.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AccommodationImages\Accommodation7\Oakford.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\add.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\delete.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\edit.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\view.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour1\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour2\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour3\caption.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour4\GFS_smederevo-trg-25-09-09-04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour5\download.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\TourImages\Tour6\GFS_smederevo-trg-25-09-09-04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\GuestImages\" />
    <Folder Include="Resources\Images\GuideImages\" />
    <Folder Include="Resources\Images\TouristImages\" />
    <Folder Include="Resources\Images\OwnerImages\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ToastNotifications" Version="2.5.1" />
    <PackageReference Include="ToastNotifications.Messages" Version="2.5.1" />
  </ItemGroup>

</Project>
